use tracing;

/// 判断是否需要在 finish 时注入恢复工具
/// 利用 LLM 智能判断文本是否被异常截断，代替硬编码关键词
#[allow(dead_code)]
pub fn should_recover(generated_text: &str, stop_reason: &str) -> Option<String> {
    // 0. stop_reason == 'length' → API 明确告知被截断，总是需要恢复
    if stop_reason == "length" {
        return Some("stop_reason=length".into());
    }

    // 1. 防止死循环：如果已经包含恢复/错误标记，直接不恢复
    if generated_text.contains("[holoProxy Recovery") || generated_text.contains("[holoProxy Error") {
        return None;
    }

    // 2. 【核心修复】硬编码拦截特定的 API 错误/超时信息
    // 防止 LLM 将“完整的错误提示”误判为“正常结束 (COMPLETE)”
    let lower_text = generated_text.to_lowercase();
    if lower_text.contains("timed out") || 
       lower_text.contains("empty or malformed response") || 
       lower_text.contains("api error") ||
       lower_text.contains("operation timed out") ||
       lower_text.contains("malformed") {
        tracing::warn!("🚨 [Recovery] Detected API Error/Timeout in text, forcing recovery bypass LLM.");
        return Some("detected API error or timeout".into());
    }

    // 3. 空文本或纯空白文本：视为异常中断，直接触发恢复
    if generated_text.trim().is_empty() {
        return Some("empty or whitespace-only text".into());
    }

    // 4. 获取当前激活的 LLM 配置
    let config = match crate::config::get_active_llm_config() {
        Some(c) => c,
        None => return Some("no active LLM config for recovery check".into()),
    };

    // 5. 开一个独立线程专门去咨询 LLM，避免阻塞主异步运行时
    let text = generated_text.to_string();
    let handle = std::thread::spawn(move || {
        // 【新增】启动 LLM 判断时打印日志
        tracing::info!("🔍 [Recovery] Starting LLM semantic check (text length: {} bytes)...", text.len());
        
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("tokio runtime for recovery check");
        
        rt.block_on(async {
            ask_llm_if_incomplete(&text, &config).await
        })
    });

    // 6. 等待线程结果
    match handle.join() {
        Ok(Some(reason)) => Some(reason),
        Ok(None) => None,
        Err(_) => Some("LLM check thread panicked".into()),
    }
}

/// 异步咨询 LLM 判断文本是否不完整
#[allow(dead_code)]
async fn ask_llm_if_incomplete(text: &str, config: &crate::types::LLMConfig) -> Option<String> {
    // 安全截取最后约 1500 字节，判断截断主要看结尾上下文，节省 Token
    let text_to_check = if text.len() > 1500 {
        let start = text.len().saturating_sub(1500);
        let mut safe_start = start;
        while safe_start < text.len() && !text.is_char_boundary(safe_start) {
            safe_start += 1;
        }
        format!("... [truncated] ...\n{}", &text[safe_start..])
    } else {
        text.to_string()
    };

    let url = format!("{}/chat/completions", config.base_url.trim_end_matches('/'));
    
    // 注入 AI Agent/Claude Code 的业务上下文
    let body = serde_json::json!({
        "model": config.model_name,
        "messages": [
            {
                "role": "system",
                "content": "You are an expert AI Agent response analyzer. The text you are analyzing is generated by an AI coding assistant (like Claude Code) interacting with a user via a proxy. \
                The assistant stops generating text in two scenarios: \
                1. NORMAL STOP: The assistant has finished its current thought, is asking the user a question, requesting confirmation, summarizing changes, or waiting for the user to test/run the code. In this case, the text is semantically complete, even if there are no tool calls. \
                2. ABNORMAL CUT-OFF: The assistant was interrupted, ran out of tokens, or got stuck mid-sentence/mid-code-block. It intended to say more or call a tool, but the text generation aborted abruptly. \
                \
                Your task: \
                - If the text is a NORMAL STOP (semantically complete, ends naturally, asks a question, provides a summary, or is a polite closing), reply with EXACTLY: COMPLETE \
                - If the text is an ABNORMAL CUT-OFF (abruptly ends mid-sentence, mid-word, mid-code-block, or is just meaningless garbage), reply with EXACTLY: INCOMPLETE"
            },
            {
                "role": "user",
                "content": format!("Analyze the following assistant output:\n\n{}", text_to_check)
            }
        ],
        "temperature": 0.0,
        "max_tokens": 10,
        "stream": false
    });

    let client = reqwest::Client::builder()
        .danger_accept_invalid_certs(!config.verify_ssl)
        .build()
        .unwrap_or_default();

    let req = client.post(&url)
        .header(config.auth_header.as_str(), format!("{}{}", config.auth_prefix, config.api_key))
        .json(&body);

    match req.send().await {
        Ok(resp) => {
            if let Ok(json) = resp.json::<serde_json::Value>().await {
                if let Some(content) = json["choices"][0]["message"]["content"].as_str() {
                    let lower = content.to_lowercase();
                    if lower.contains("incomplete") {
                        return Some("LLM judged text as abnormally cut-off".into());
                    }
                }
            }
            None
        }
        Err(e) => {
            tracing::warn!("Recovery LLM check failed: {}", e);
            None 
        }
    }
}

/// 动态选取恢复工具：优先 Bash/Shell/RunCommand/Execute
pub fn pick_recovery_tool(
    valid_tools: &std::collections::HashMap<String, &crate::types::ToolDef>,
) -> Option<(String, serde_json::Value)> {
    if valid_tools.is_empty() {
        return None;
    }
    let priority_names = [
        "Bash", "Shell", "bash", "shell",
        "Execute", "Run_Command", "RunCommand", "terminal", "Terminal",
    ];
    for name in &priority_names {
        if let Some(tool) = valid_tools.get(*name) {
            return Some((name.to_string(), build_recovery_args(tool)));
        }
    }
    for (name, tool) in valid_tools.iter() {
        let props = tool.input_schema.as_ref()
            .and_then(|s| s.get("properties"))
            .and_then(|p| p.as_object());
        if let Some(props_map) = props {
            if props_map.contains_key("command") {
                return Some((name.clone(), serde_json::json!({
                    "command": "echo \"Fake tool calling ...\" && pwd && ls -la || cd && dir"
                })));
            }
        }
    }
    let (name, tool) = valid_tools.iter().next().unwrap();
    Some((name.clone(), build_recovery_args(tool)))
}

fn build_recovery_args(tool: &crate::types::ToolDef) -> serde_json::Value {
    let props = tool.input_schema.as_ref()
        .and_then(|s| s.get("properties"))
        .and_then(|p| p.as_object());
    if let Some(props_map) = props {
        if props_map.contains_key("command") {
            return serde_json::json!({"command": "echo \"Fake tool calling ...\" && pwd && ls -la || cd && dir"});
        }
        if props_map.contains_key("path") {
            return serde_json::json!({"path": "./"});
        }
        if props_map.contains_key("query") {
            return serde_json::json!({"query": "*"});
        }
        if let Some((first_key, _)) = props_map.iter().next() {
            return serde_json::json!({first_key: "echo recovery"});
        }
    }
    serde_json::json!({})
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_should_recover_length() {
        assert!(should_recover("some text", "length").is_some());
    }

    #[test]
    fn test_prevent_infinite_loop() {
        assert!(should_recover("[holoProxy Recovery] some text", "stop").is_none());
    }

    #[test]
    fn test_empty_text_recovery() {
        assert!(should_recover("", "stop").is_some());
        assert!(should_recover("   \n\t  ", "stop").is_some());
    }

    #[test]
    fn test_api_error_intercept() {
        // 验证新增的硬编码拦截是否生效
        assert!(should_recover("API Error: The operation timed out.", "stop").is_some());
        assert!(should_recover("API Error: API returned an empty or malformed response (HTTP 200)", "stop").is_some());
        assert!(should_recover("Some normal text. API Error occurred.", "stop").is_some());
    }
}