use tracing;

/// 判断是否需要在 finish 时注入恢复工具
/// 硬编码拦截 + LLM 智能判断双保险
pub fn should_recover(generated_text: &str, stop_reason: &str) -> Option<String> {
    // 0. stop_reason == 'length' → API 明确告知被截断，总是需要恢复
    if stop_reason == "length" {
        return Some("stop_reason=length".into());
    }

    // 1. 防止死循环：如果已经包含恢复/错误标记，直接不恢复
    if generated_text.contains("[holoProxy Recovery") || generated_text.contains("[holoProxy Error") {
        return None;
    }

    // 2. 硬编码拦截 API 错误/超时/网关异常关键词
    // 防止 LLM 将"完整的错误提示"误判为"正常结束 COMPLETE"
    let lower_text = generated_text.to_lowercase();
    if lower_text.contains("timed out")
        || lower_text.contains("empty or malformed response")
        || lower_text.contains("api error")
        || lower_text.contains("operation timed out")
        || lower_text.contains("malformed")
        || lower_text.contains("connection")
        || lower_text.contains("unreachable")
        || lower_text.contains("502")
        || lower_text.contains("503")
        || lower_text.contains("504")
        || lower_text.contains("gateway")
        || lower_text.contains("proxy error")
        || lower_text.contains("internal server error")
    {
        tracing::warn!(
            "🚨 [Recovery] 硬编码拦截触发 | snippet={}",
            &generated_text[..generated_text.len().min(200)]
        );
        return Some("detected API error or timeout".into());
    }

    // 3. 空文本或纯空白文本：视为异常中断，直接触发恢复
    if generated_text.trim().is_empty() {
        return Some("empty or whitespace-only text".into());
    }

    // 4. 获取当前激活的 LLM 配置
    let config = match crate::config::get_active_llm_config() {
        Some(c) => c,
        None => return Some("no active LLM config for recovery check".into()),
    };

    // 5. 开一个独立线程专门去咨询 LLM，避免阻塞主异步运行时
    let text = generated_text.to_string();
    let handle = std::thread::spawn(move || {
        tracing::info!(
            "🔍 [Recovery] LLM 语义判断启动 | text_len={}B",
            text.len()
        );

        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("tokio runtime for recovery check");

        rt.block_on(async { ask_llm_if_incomplete(&text, &config).await })
    });

    // 6. 等待线程结果
    match handle.join() {
        Ok(Some(reason)) => Some(reason),
        Ok(None) => None,
        Err(_) => Some("LLM check thread panicked".into()),
    }
}

/// 异步咨询 LLM 判断文本是否不完整
async fn ask_llm_if_incomplete(text: &str, config: &crate::types::LLMConfig) -> Option<String> {
    // 安全截取最后约 1500 字节，判断截断主要看结尾上下文，节省 Token
    let text_to_check = if text.len() > 1500 {
        let start = text.len().saturating_sub(1500);
        let mut safe_start = start;
        while safe_start < text.len() && !text.is_char_boundary(safe_start) {
            safe_start += 1;
        }
        format!("... [truncated] ...\n{}", &text[safe_start..])
    } else {
        text.to_string()
    };

    let url = format!("{}/chat/completions", config.base_url.trim_end_matches('/'));

    // 增强版 prompt：明确定义三类场景 + API 错误/超时识别
    let body = serde_json::json!({
        "model": config.model_name,
        "messages": [
            {
                "role": "system",
                "content": "You are an expert AI Agent response quality analyzer. Your job is to decide if a response needs emergency recovery (fake tool call injection) to prevent the agent from crashing.\n\
The text you analyze is generated by an AI coding assistant (like Claude Code) interacting with a user via proxy.\n\
\n\
There are THREE scenarios:\n\
\n\
1. NORMAL STOP (reply COMPLETE):\n\
   - The assistant finished its thought naturally, summarized work, asked a question, requested user action, or gave a polite closing.\n\
   - The text is semantically complete, ends with a natural conclusion.\n\
   - Examples: \"总结：脚本可以自动处理...等你有新的退费单后再运行\", \"以上就是今天的分析，有什么问题吗？\", \"任务完成了。\"\n\
\n\
2. API / NETWORK ERROR TEXT (reply INCOMPLETE):\n\
   - The text describes an HTTP error, timeout, gateway failure, connection issue, empty response, or any API-level failure.\n\
   - The content looks like an error message from a proxy, gateway, or server (NOT a normal conversation).\n\
   - Examples: \"API Error: API returned an empty or malformed response (HTTP 200)\", \"The operation timed out.\", \"502 Bad Gateway\", \"Connection refused\", \"Internal Server Error\".\n\
   - Key signal: the text is a server/system error message, not a normal assistant reply. THIS ALWAYS NEEDS RECOVERY.\n\
\n\
3. ABNORMAL CUT-OFF (reply INCOMPLETE):\n\
   - The assistant was interrupted mid-sentence, mid-word, mid-code-block, or mid-thought.\n\
   - The text ends abruptly without any natural closure.\n\
   - Examples: \"The solution is to imp\", \"Here's the code:\\n```python\\ndef main():\", \"Let me explain the\"\n\
\n\
YOUR TASK: Read the text carefully. Reply EXACTLY one word:\n\
- COMPLETE  → scenarios 1\n\
- INCOMPLETE → scenarios 2 or 3"
            },
            {
                "role": "user",
                "content": format!("Analyze this assistant output:\n\n{}", text_to_check)
            }
        ],
        "temperature": 0.0,
        "max_tokens": 10,
        "stream": false
    });

    let client = reqwest::Client::builder()
        .danger_accept_invalid_certs(!config.verify_ssl)
        .build()
        .unwrap_or_default();

    let req = client
        .post(&url)
        .header(
            config.auth_header.as_str(),
            format!("{}{}", config.auth_prefix, config.api_key),
        )
        .json(&body);

    match req.send().await {
        Ok(resp) => {
            if let Ok(json) = resp.json::<serde_json::Value>().await {
                if let Some(content) = json["choices"][0]["message"]["content"].as_str() {
                    let lower = content.to_lowercase();
                    let verdict = if lower.contains("incomplete") {
                        "INCOMPLETE"
                    } else {
                        "COMPLETE"
                    };
                    tracing::info!(
                        "🧠 [Recovery] LLM 判断结果: {} | raw={}",
                        verdict,
                        content.trim()
                    );
                    if lower.contains("incomplete") {
                        return Some("LLM judged text as abnormally cut-off".into());
                    }
                    // LLM 判断为 COMPLETE → 不注入恢复
                    tracing::info!("✅ [Recovery] LLM 判断为正常结束，跳过恢复");
                }
            }
            None
        }
        Err(e) => {
            tracing::warn!("❌ [Recovery] LLM 判断请求失败: {}，默认不恢复", e);
            None
        }
    }
}

/// 动态选取恢复工具：优先 Bash/Shell/RunCommand/Execute
pub fn pick_recovery_tool(
    valid_tools: &std::collections::HashMap<String, &crate::types::ToolDef>,
) -> Option<(String, serde_json::Value)> {
    if valid_tools.is_empty() {
        return None;
    }
    let priority_names = [
        "Bash", "Shell", "bash", "shell",
        "Execute", "Run_Command", "RunCommand", "terminal", "Terminal",
    ];
    for name in &priority_names {
        if let Some(tool) = valid_tools.get(*name) {
            return Some((name.to_string(), build_recovery_args(tool)));
        }
    }
    for (name, tool) in valid_tools.iter() {
        let props = tool
            .input_schema
            .as_ref()
            .and_then(|s| s.get("properties"))
            .and_then(|p| p.as_object());
        if let Some(props_map) = props {
            if props_map.contains_key("command") {
                return Some((
                    name.clone(),
                    serde_json::json!({
                        "command": "echo \"Fake tool calling ...\" && pwd && ls -la || cd && dir"
                    }),
                ));
            }
        }
    }
    let (name, tool) = valid_tools.iter().next().unwrap();
    Some((name.clone(), build_recovery_args(tool)))
}

fn build_recovery_args(tool: &crate::types::ToolDef) -> serde_json::Value {
    let props = tool
        .input_schema
        .as_ref()
        .and_then(|s| s.get("properties"))
        .and_then(|p| p.as_object());
    if let Some(props_map) = props {
        if props_map.contains_key("command") {
            return serde_json::json!({"command": "echo \"Fake tool calling ...\" && pwd && ls -la || cd && dir"});
        }
        if props_map.contains_key("path") {
            return serde_json::json!({"path": "./"});
        }
        if props_map.contains_key("query") {
            return serde_json::json!({"query": "*"});
        }
        if let Some((first_key, _)) = props_map.iter().next() {
            return serde_json::json!({first_key: "echo recovery"});
        }
    }
    serde_json::json!({})
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_should_recover_length() {
        assert!(should_recover("some text", "length").is_some());
    }

    #[test]
    fn test_prevent_infinite_loop() {
        assert!(should_recover("[holoProxy Recovery] some text", "stop").is_none());
    }

    #[test]
    fn test_empty_text_recovery() {
        assert!(should_recover("", "stop").is_some());
        assert!(should_recover(" \n\t ", "stop").is_some());
    }

    #[test]
    fn test_api_error_intercept() {
        // 验证硬编码拦截 API 错误/超时关键词
        assert!(should_recover("API Error: The operation timed out.", "stop").is_some());
        assert!(should_recover("API Error: API returned an empty or malformed response (HTTP 200)", "stop").is_some());
        assert!(should_recover("Some normal text. API Error occurred.", "stop").is_some());
        assert!(should_recover("502 Bad Gateway", "stop").is_some());
        assert!(should_recover("Connection refused", "stop").is_some());
        assert!(should_recover("Internal Server Error", "stop").is_some());
    }
}
